### ISSUE TITLE
Tooltip gets stuck

### ISSUE THREAD

**Issue by comertcimen** [KevinVandy/mantine-react-table#10]
### mantine-react-table version

0.9.2

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When the element goes to disabled state, the tooltip wrapping that element stucks in the page.

Is there a way to completely disable tooltips?

Can be reproduced by filling the search box and clicking the clear (x) button

<img width="405" alt="Screenshot 2023-02-16 at 10 52 28" src="https://user-images.githubusercontent.com/5621612/219332781-e620a8e4-c963-450c-9ac4-500669f6acef.png">
<img width="380" alt="Screenshot 2023-02-16 at 10 52 41" src="https://user-images.githubusercontent.com/5621612/219332821-8b22fcd2-3995-45ca-9c45-cf213a9527f3.png">

### Minimal, Reproducible Example - (Optional, but Recommended)

[Codesandbox](https://codesandbox.io/s/github/KevinVandy/mantine-react-table/tree/main/apps/mantine-react-table-docs/examples/customize-global-filter-component/sandbox?file=/src/TS.tsx)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by joshrosenblum** [comment]
Encountered the same bug using the Global Filter input. Once I've typed into it, the "Clear Search" tooltip never goes away.

<img width="322" alt="Screenshot 2023-02-26 at 2 50 33 PM" src="https://user-images.githubusercontent.com/32690393/221433598-5ace3cbf-261a-4f40-ba16-1bf1af720408.png">

As an aside, thanks @KevinVandy for this absolutely awesome component and documentation! So helpful.

**Comment by joshrosenblum** [comment]
I took a quick look at this one - straightforward fix. I submitted a PR #13.
