### ISSUE TITLE
french translation error 

### ISSUE THREAD

**Issue by ghost** [KevinVandy/mantine-react-table#123]
### mantine-react-table version

V6.0.21

### react & react-dom versions

V18.2.0

### Describe the bug and the steps to reproduce it

`5 de 5 ligne(s)` is wrong translation in french.

We can say `5 sur 5 ligne(s)`.

### Minimal, Reproducible Example - (Optional, but Recommended)

You can add an key for this in the local file for fix. 

The other uses of  key "of" are correct.

### Screenshots or Videos (Optional)

![Capture d’écran du 2023-09-19 10-45-40](https://github.com/KevinVandy/mantine-react-table/assets/120370047/7b942786-efc0-4faf-9617-702ef548f64d)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by sanchezweezer** [comment]
test

**Comment by KevinVandy** [comment]
fixed by https://github.com/KevinVandy/mantine-react-table/commit/bab0c546836a4bb919227e4ded52a98f8399bce8
