### ISSUE TITLE
Something went wrong with a type "MRT_TableOptions<T>" after 1.3.0

### ISSUE THREAD

**Issue by ctretyak** [KevinVandy/mantine-react-table#148]
### mantine-react-table version

1.3.1

### react & react-dom versions

18.2

### Describe the bug and the steps to reproduce it

After update to 1.3.1 VSCode doesn't show suggestions on variables typed with MRT_TableOptions<T> where T extends Record<string, any>
1.3.1:
![image](https://github.com/KevinVandy/mantine-react-table/assets/4935982/7518e0a1-b15e-43f3-81d1-09aac675a7fb)
1.2.1:
![image](https://github.com/KevinVandy/mantine-react-table/assets/4935982/c67d3ad7-fcdd-491b-9709-df7713d42b6a)

### Minimal, Reproducible Example - (Optional, but Recommended)

install 1.3.1 and ctrl+space on any variable typed with MRT_TableOptions<T> where T extends Record<string, any>

```
import { MRT_TableOptions } from "mantine-react-table";

export function useMRTFormValidation<T extends Record<string, any>>(
    options: MRT_TableOptions<T>,
): typeof options {

    return {

    } as MRT_TableOptions<T>;
}
```

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I don't know why this is happening. Though it appears that the useMantineReactTable hook and MantineReactTable component are still working fine.

**Comment by ctretyak** [comment]
something local. It's okay on codesandbox.
https://codesandbox.io/s/determined-dew-qpmzqs?file=/src/App.tsx
