### ISSUE TITLE
Drag and drop is not working

### ISSUE THREAD

**Issue by jooyeal** [KevinVandy/mantine-react-table#15]
### mantine-react-table version

v0.9.3

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

when i using props about column or row drag with other library called react-dnd-treeview or react-arborist, drag and drop is not working. i think react-dnd is conflicting. could you please check this bug?

### Minimal, Reproducible Example - (Optional, but Recommended)

.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
There was a duplicate convo a while ago in the mui version of this library https://github.com/KevinVandy/material-react-table/issues/102

There are some solutions discussed here https://github.com/react-dnd/react-dnd/issues/3304

This is an issue caused by react-dnd itself
