### ISSUE TITLE
can't seem to use the built in mantine-react-table typescript definition 

### ISSUE THREAD

**Issue by adhamaa** [KevinVandy/mantine-react-table#18]
### mantine-react-table version

0.94

### react & react-dom versions

^18.2.0

### Describe the bug and the steps to reproduce it

after cleaning my node_modules it happens,
before u can import the type definition from the package without type error or need to install extra packages

### Minimal, Reproducible Example - (Optional, but Recommended)

![image](https://user-images.githubusercontent.com/50027371/223628009-8dae6ecc-b6f6-4ae1-9efc-80c061420759.png)

### Screenshots or Videos (Optional)

![image](https://user-images.githubusercontent.com/50027371/223627576-71f79203-fc8b-4f6f-9c3c-d3af06258908.png)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by akashaf** [comment]
`index.d.ts` is missing from `dist` folder.

**Comment by rick427** [comment]
Am having the same issue in a Typescript project

**Comment by KevinVandy** [comment]
sorry folks. Don't know how that happened. Just rebuilt and published v0.9.5 and there seems to be no issue anymore

**Comment by akashaf** [comment]
> sorry folks. Don't know how that happened. Just rebuilt and published v0.9.5 and there seems to be no issue anymore

Issue resolved and tested. no more issue. Thanks @KevinVandy .

**Comment by adhamaa** [comment]
Thanks @KevinVandy, I'll be closing this issues as it had been fixed...
