### ISSUE TITLE
Table not Display properly

### ISSUE THREAD

**Issue by ibadi-id** [KevinVandy/mantine-react-table#187]
### mantine-react-table version

v2.0.0-alpha.5

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

The current table display on the v2.0.0-alpha.5 does not display properly like in documentation

### Minimal, Reproducible Example - (Optional, but Recommended)

https://github.com/KevinVandy/mantine-react-table/tree/v1/apps/mantine-react-table-docs/examples/editing-crud-table

### Screenshots or Videos (Optional)

<img width="896" alt="image" src="https://github.com/KevinVandy/mantine-react-table/assets/82359656/e13cd005-34c6-4283-9bee-cc3161ac481e">

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Looks like you are not importing 'material-react-table/styles.css'.

There will be better instructions and docs for this soon

**Comment by ibadi-id** [comment]
oke thank you it's worked

**import 'mantine-react-table/styles.css';**

<img width="902" alt="image" src="https://github.com/KevinVandy/mantine-react-table/assets/82359656/d782b26d-8747-4f70-9f22-830ce1dcb397">
