### ISSUE TITLE
Color schemes not working with mantine v7

### ISSUE THREAD

**Issue by lukasbash** [KevinVandy/mantine-react-table#192]
### mantine-react-table version

v1.3.3

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Using mantine version v7.1.5 and the corresponding colorscheme mechanism:
```typescript
const { toggleColorScheme, colorScheme } = useMantineColorScheme();
```
The table does not re-render, based on this change.

Actually even simpler using the mantine provider like this:
```jsx
<MantineProvider forceColorScheme="dark">
```
the table still stays in light mode. Wrapping the table in another provider, changing the values there also has no effect.

### Minimal, Reproducible Example - (Optional, but Recommended)

.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by posabsolute** [comment]
v1.3.3 is not compatible with mantine v7, you will need to use the alpha, I will close the issue but feel free to re-open if you have this issue with v2
