### ISSUE TITLE
✘ [ERROR] No matching export in "node_modules/@mantine/core/esm/index.js" for import "packSx"

### ISSUE THREAD

**Issue by bikashjr** [KevinVandy/mantine-react-table#199]
### mantine-react-table version

1.3.4

### react & react-dom versions

18.2.0 

### Describe the bug and the steps to reproduce it

```
import { useMemo } from 'react';
import { MantineReactTable, useMantineReactTable } from 'mantine-react-table';
```

While importing this code I got following error.
<img width="684" alt="Screenshot 2023-12-01 at 15 38 33" src="https://github.com/KevinVandy/mantine-react-table/assets/134906057/3bd824dc-c685-4dab-9fb6-3697cee948bf">

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/nice-curran-vp99z6?file=%2Fsrc%2Findex.js%3A53%2C7-53%2C14

### Screenshots or Videos (Optional)

<img width="684" alt="Screenshot 2023-12-01 at 15 38 33" src="https://github.com/KevinVandy/mantine-react-table/assets/134906057/e755b1ae-41ed-45e0-9b67-782c382a7000">

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by BhabukAdhikari** [comment]
@bikashjr I am also getting same error any solution for this??

**Comment by KevinVandy** [comment]
This is because of mismatching Mantine versions. Guessing you tried to install Mantine v7 for MRT v1

**Comment by bikashjr** [comment]
thanks for information ..
