### ISSUE TITLE
404 on documentation

### ISSUE THREAD

**Issue by ruslanguns** [KevinVandy/mantine-react-table#2]
### mantine-react-table version

.

### react & react-dom versions

.

### Describe the bug and the steps to reproduce it

Website documentation is giving 404, I don't know whether or not because you have this is a private project on Vercel. 

### Minimal, Reproducible Example - (Optional, but Recommended)

Open https://www.mantine-react-table.com/ in the browser returns 404

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
The website is not up yet, but you can run the docs site locally if you want while it's in alpha

**Comment by ruslanguns** [comment]
Understood! I thought it was unexpected. Thank you!

**Comment by KevinVandy** [comment]
> Understood! I thought it was unexpected. Thank you!

People are finding this faster than I thought. Guess the npm readme is starting to rank in Google now?

**Comment by ruslanguns** [comment]
@KevinVandy Congratulations on your excellent work in combining an attractive user interface with (Mantine UI) and a powerful library like React Table. The agnosticism of the integration is particularly impressive. Keep up the great work!

**Comment by KevinVandy** [comment]
@ruslanguns I just got the site to build and deploy live, but with a disclaimer that this is still in alpha

https://www.mantine-react-table.com/

Advanced filtering features in particular are still going through big changes before stable release

**Comment by ruslanguns** [comment]
@KevinVandy wonderful! Thank you mate!
