### ISSUE TITLE
sticky custom Footer displays a footer with transparent background

### ISSUE THREAD

**Issue by posabsolute** [KevinVandy/mantine-react-table#206]
### mantine-react-table version

v2-alpha

### react & react-dom versions

v18.0.2

### Describe the bug and the steps to reproduce it

* Sticky custom Footer displays a footer with transparent background
* Custom Footer isn’t displayed under corresponding column

See https://v2.mantine-react-table.com/docs/guides/aggregation-and-grouping#aggregation-grouping-example

### Minimal, Reproducible Example - (Optional, but Recommended)

-

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
This was fixed in #201
