### ISSUE TITLE
Global column ordering dosent have the dotted border and wrong spacing

### ISSUE THREAD

**Issue by posabsolute** [KevinVandy/mantine-react-table#212]
### mantine-react-table version

v2-alpha

### react & react-dom versions

v18.0.2

### Describe the bug and the steps to reproduce it

Reorder column using global filter with this demo https://v2.mantine-react-table.com/docs/guides/column-ordering-dnd#enable-column-ordering-demo

### Minimal, Reproducible Example - (Optional, but Recommended)

-

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Could you please add a screenshot/video of what is wrong? I've been looking to v1 & v2 side-to-side and the only missing thing I can notice is the box shadow for the headers when dragging.

**Comment by posabsolute** [comment]
@alessandrojcm  here the screenshow

<img width="1444" alt="Screenshot 2023-12-06 at 10 56 57 AM" src="https://github.com/KevinVandy/mantine-react-table/assets/114950/348f646b-cbdc-4b09-81ee-4e6b86e8a06c">

Try dragging in v1 and v2, you will see v1 show where it will drop and also the hover effect, the spacing is wrong
