### ISSUE TITLE
Warning: Check the render method of `@mantine/core/Tooltip` with Mantine 7 and MRT V2

### ISSUE THREAD

**Issue by bruskadev** [KevinVandy/mantine-react-table#215]
### mantine-react-table version

v2.0.0-alpha.4

### react & react-dom versions

^18.2.0

### Describe the bug and the steps to reproduce it

On the project we use Mantine UI library v7.3.0 and Mantine React Table, everything works fine but the console displays Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `@mantine/core/Tooltip`. 

Which is a bit annoying. Is it possible to fix it? 

### Minimal, Reproducible Example - (Optional, but Recommended)

<img width="788" alt="Снимок экрана 2023-12-07 в 15 15 10" src="https://github.com/KevinVandy/mantine-react-table/assets/151489011/af9ff5ab-efbb-48a7-b141-547311601635">

### Screenshots or Videos (Optional)

<img width="788" alt="Снимок экрана 2023-12-07 в 15 15 10" src="https://github.com/KevinVandy/mantine-react-table/assets/151489011/15283500-28d5-4fda-912d-d98f2545405a">

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Which features have you enabled when you see this warning?

**Comment by hamza-arshad-mughal** [comment]
tooltip is trying to pass in reference to a child component. for that you must change your child component into forwarded component. using React.forwardRef
