### ISSUE TITLE
Cannot use date-range filterVariant

### ISSUE THREAD

**Issue by aaronsmulktis** [KevinVandy/mantine-react-table#23]
### mantine-react-table version

v0.9.3

### react & react-dom versions

v17.0.2 & v17.0.1

### Describe the bug and the steps to reproduce it

Awesome work! This is a fantastic plugin and I'm super thankful to have found this.

Just wrestling with date-range filtering, setting `filterVariant` to `date-range` does not show a date range picker for filtering by date ranges as [the docs suggest](https://www.mantine-react-table.com/docs/guides/column-filtering#filter-variants), but rather shows the default `TextInput` component.

Even with manually defining the `DatePicker` component for both `Filter` and `Filter2` in the column definition, the `DatePicker` components display correctly but do not filter correctly, even when manually calling `column.setFilterValue(newValue)` on the `onChange` props (respectively).

### Minimal, Reproducible Example

https://codesandbox.io/p/sandbox/zen-bhabha-9fz4hy?file=%2Fsrc%2FTS.tsx

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
date-range was added to the types, but currently renders null. I just published a 1.0.0-beta version with the plans to use Mantine Dates v6 built-in, but having some z-index issues with the v6 upgrade. More to come.

**Comment by KevinVandy** [comment]
Finally built-in date and date-range filters variants and released them in `v1.0.0-beta.9`

**Comment by aaronsmulktis** [comment]
Really appreciate you and this beastly library!
