### ISSUE TITLE
header is not sticky despite enableStickyHeader prop being true

### ISSUE THREAD

**Issue by abenhamdine** [KevinVandy/mantine-react-table#233]
### mantine-react-table version

2.0.0-alpha.9

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

We use MRT with mantine 7.3.2, with Next.js 14.0.4 

Despite `enableStickyHeader` being true, the table header is not fixed, only the global actions header.

Here's the component we use :   

```tsx
'use client'
import {
    MantineReactTable,
} from 'mantine-react-table'

export const DataTable: React.FC<Props> = ({ data, columns }) => {
    return <MantineReactTable
        localization={MRT_Localization_FR}
        columns={columns}
        data={data}
        enableStickyHeader
        enableStickyFooter
        enablePagination={false}
        enableDensityToggle={false}
        enableColumnDragging={false}
        enableFullScreenToggle={false}
        enableRowVirtualization={true}
        rowVirtualizerOptions={{
            overscan: 8
        }}
        initialState={{ density: 'xs' }}
        enableRowSelection
        enableColumnOrdering
        enableGlobalFilter
        enableColumnResizing
        columnResizeMode="onEnd"
    />
}
```

Something is putting `position: relative` on the header as shown in the screen shot : 
<img width="900" alt="image" src="https://github.com/KevinVandy/mantine-react-table/assets/7466144/cfa8cf4e-2434-4142-a78d-aeec17ecbf58">

I managed to workaround this by overriden position with a css, but of course it's not ideal : 

```css
.mrt-table .thead {
    position: sticky !important;
}
```

### Minimal, Reproducible Example - (Optional, but Recommended)

I will try to add a sandbox later

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
This was fixed in #227, it just hasn't been released yet.
