### ISSUE TITLE
Cannot install mantine-react-table v2

### ISSUE THREAD

**Issue by waaiu** [KevinVandy/mantine-react-table#236]
### mantine-react-table version

1

### react & react-dom versions

18

### Describe the bug and the steps to reproduce it

How to install mantine-react-table v2

### Minimal, Reproducible Example - (Optional, but Recommended)

.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This was a very vague issue, but try out at least version v2.0.0-alpha.13 to see if that works. I just redid some ESM configurations.
