### ISSUE TITLE
Footer cells doesn't align with columns in V2

### ISSUE THREAD

**Issue by highviolet** [KevinVandy/mantine-react-table#245]
### mantine-react-table version

2.0.0-alpha.10

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Footer cells doesn't align with their columns.
This issue is present on the docs site in the [Aggregation and Grouping Example](https://v2.mantine-react-table.com/docs/examples/aggregation-and-grouping#aggregation-and-grouping-example).

### Minimal, Reproducible Example - (Optional, but Recommended)

-

### Screenshots or Videos (Optional)

![footer_col_alignment](https://github.com/KevinVandy/mantine-react-table/assets/45597004/c12c59a2-a50e-4d50-895c-04a0220fcbdf)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by snturk** [comment]
Can you check it again? I'm not seeing any issue either in storybook samples or the docs.

**Comment by highviolet** [comment]
Seems to have been fixed by a recent commit. Docs looks good now.
Closing.
