### ISSUE TITLE
Localization gives "Failed to resolve import... Does that file exist?"

### ISSUE THREAD

**Issue by FurkanCodes** [KevinVandy/mantine-react-table#253]
### mantine-react-table version

2.0.0-alpha.14

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I am following the code on the docs but it throws `"[plugin:vite:import-analysis] Failed to resolve import "mantine-react-table/locales/es" from "src\components\DataTable.tsx". Does the file exist?"`

### Minimal, Reproducible Example - (Optional, but Recommended)

```

import 'mantine-react-table/styles.css'; //make sure MRT styles were imported in your app root (once)
//Import Mantine React Table and its Types
import { MantineReactTable, type MRT_ColumnDef } from 'mantine-react-table'; 

//Import Mantine React Table Translations
import { MRT_Localization_ES } from 'mantine-react-table/locales/es';

//mock data
import { data, type Person } from '../makeData';

const columns: MRT_ColumnDef<Person>[] = [
  {
    accessorKey: 'firstName',
    header: 'Primer nombre',
  },
  {
    accessorKey: 'lastName',
    header: 'Apellido',
    enableClickToCopy: true,
  },
  {
    accessorKey: 'age',
    header: 'Años',
  },
];

const Example = () => {
  return (
    <MantineReactTable
      columns={columns}
      data={data}
      enableColumnFilterModes
      enableColumnOrdering
      enableEditing
      enableColumnPinning
      enableRowActions
      enableRowSelection
      enableSelectAll={false}
      initialState={{ showColumnFilters: true, showGlobalFilter: true }}
      localization={MRT_Localization_ES}
    />
  );
};

export default Example;
```

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by FurkanCodes** [comment]
I managed to bruteforce this by copying the localization package at "node_modules\mantine-react-table\locales\tr\index.js" to my projects i18n folder, then imported that on my datatable. I don't think this is the intended usage though.

**Comment by KevinVandy** [comment]
<img width="1223" alt="image" src="https://github.com/KevinVandy/mantine-react-table/assets/28243511/fa4cdf1c-db40-4c7b-9390-37b8b7d751d8">

**Comment by FurkanCodes** [comment]
I have totally missed it. Thanks!

**Comment by KevinVandy** [comment]
I think I'm going to redo some export stuff in the package.json to not make it a problem for anyone.
