### ISSUE TITLE
Selection + Action columns not displayed right, when displayed together

### ISSUE THREAD

**Issue by juliuslipp** [KevinVandy/mantine-react-table#26]
### mantine-react-table version

v1.0.0-beta

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

When displaying row selection as well as row actions, the selection column as well as the action column grow in size, when they shouldn't. The checkboxes also don't have a pointer as cursor.

How to reproduce:
Set the following props:
```
  enableRowSelection
  enableRowActions
  positionActionsColumn="last"
  renderRowActions={(rowActionProps) => {
    const { row } = rowActionProps;

    return <div>row.original</div>;
  }}
```

### Minimal, Reproducible Example - (Optional, but Recommended)

Add the props to the following example:
https://stackblitz.com/github/KevinVandy/mantine-react-table/tree/main/apps/mantine-react-table-docs/examples/enable-row-selection/sandbox?file=src%2FTS.tsx

### Screenshots or Videos (Optional)

<img width="1241" alt="Screenshot 2023-03-31 at 12 27 00" src="https://user-images.githubusercontent.com/43986145/229098406-e891e648-1486-4bd3-9127-7b88c532385d.png">

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I'm not really seeing any problems here. No weird column sizes. Also the mantine checkbox cusor pointer thing is a Mantine theme config that is off by default.
