### ISSUE TITLE
Error in React Query (Remote) Example 

### ISSUE THREAD

**Issue by Sergey7709** [KevinVandy/mantine-react-table#263]
### mantine-react-table version

v2

### react & react-dom versions

-

### Describe the bug and the steps to reproduce it

Error in React Query (Remote) Example  in https://v2.mantine-react-table.com/docs/examples/react-query

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/~/github_project/KevinVandy/material-react-table/tree/v2/apps/material-react-table-docs/examples/react-query/sandbox?file=src%2FTS.tsx

### Screenshots or Videos (Optional)

![0](https://github.com/KevinVandy/mantine-react-table/assets/116739566/b15e2a1c-091c-48b3-9368-b17b6ab0b6a2)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I'm aware. It will be like that until I move it to the main domain

**Comment by Sergey7709** [comment]
Thanks for the reply!
