### ISSUE TITLE
"popover" columnFilterDisplayMode does not seem to work with filterVariant: select

### ISSUE THREAD

**Issue by ericblade** [KevinVandy/mantine-react-table#269]
### mantine-react-table version

2.0.0-alpha.16

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

The popover comes up, but selecting anything in the select drop down, or entering text, fails to actually run the filter.

This is also visible in the popover example in the documentation.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://v2.mantine-react-table.com/docs/guides/column-filtering#alternate-column-filtering-demo

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Hey, can you try with the `beta.0` and confirm is this is still an issue?

**Comment by ericblade** [comment]
If the documentation site has been updated, then it's still an issue.  I hope to have some time to check it out on my personal app this weekend sometime.  Thanks for the notice, and I'll let you know as soon as I have a chance.

**Comment by waltershewmake** [comment]
I am experiencing this issue on 2.0.0-beta.1

**Comment by waltershewmake** [comment]
Presumably, this is because there is no way to stop event propagation from the Mantine Select field dropdown without rewriting it using a custom ComboBox implementation (as far as I am aware).  For the same reason, this issue is likely also present in the autocomplete filter variant, which uses a ComboBox under the hood as well.

**Comment by waltershewmake** [comment]
Actually, I just found a solution. I will fork and propose a fix. In `MRT_FilterTextInput` you can wrap the entire return block with 
```tsx
<div onMouseDown={(e) => e.stopPropagation()}>
...
</div>
```

**Comment by alessandrojcm** [comment]
Merged, thanks @waltershewmake

**Comment by ericblade** [comment]
Apologies it took me a few .. months... :( to check in on this, just got my app back up now that i've got some time off from work.  Time now to update all the dependencies, and I'll check this out.  If it's still a problem, I'll reopen.

Thank you so much!

**Comment by Angel-Manchev** [comment]
Did you fix this problem, because i am still experiencing it
