### ISSUE TITLE
"renderedColumnIndex" warning on Row Edit

### ISSUE THREAD

**Issue by sjbouwman** [KevinVandy/mantine-react-table#270]
### mantine-react-table version

2.0.0-alpha.17

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

A warning appears when clicking on the Edit button if trying to edit a row (editDisplayMode="row"). This bug can also be seen in one of the "official" example codepens. 

![mantine-table-bug](https://github.com/KevinVandy/mantine-react-table/assets/45181109/d0a99f6d-cf17-4156-bf6f-01d626adba6e)

### Minimal, Reproducible Example - (Optional, but Recommended)

Error start to appear when one of the columns gets the "enableEditing: true" prop.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Just a warning of an extra prop getting through. Feel free to PR the fix, else I'll get to it in a few days

**Comment by KevinVandy** [comment]
This should be fixed in v2-beta.0
