### ISSUE TITLE
Docs site is down - Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by ikx94** [KevinVandy/mantine-react-table#276]
### mantine-react-table version

v.1.3.4

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

The v2 documentation site is down.

Getting a message that says: "Application error: a client-side exception has occurred (see the browser console for more information)."

And in the console:

_app-599db1e8db8457c7.js:4  Error: @mantine/core: MantineProvider was not found in component tree, make sure you have it in your app

### Minimal, Reproducible Example - (Optional, but Recommended)

Visit the v2 docs site.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Pay attention to the commits and you'll see that I've been trying to fix it
