### ISSUE TITLE
Action dropdown menu not fully visible with virtualisation enabled

### ISSUE THREAD

**Issue by petrmacal** [KevinVandy/mantine-react-table#29]
### mantine-react-table version

v0.9.5

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

When the virtualisation in ON (`enableColumnVirtualization`, `enableRowVirtualization` flags enabled), and in the same time `renderRowActionMenuItems` defined with any number of Menu items, the menu dropdown is cropped and the visible part reflects the boundaries of the cell with the action activator. The rest of the content is hidden.

The menu dropdown is displayed corretly with the virtualisation disabled.

### Minimal, Reproducible Example - (Optional, but Recommended)

See the screenshots.

### Screenshots or Videos (Optional)

<img width="157" alt="Screenshot 2023-04-04 at 11 03 32" src="https://user-images.githubusercontent.com/31385204/229743292-d7302f11-58c5-467c-acf1-e94621d5c0e2.png">

<img width="321" alt="Screenshot 2023-04-04 at 11 04 07" src="https://user-images.githubusercontent.com/31385204/229743310-8a6d1011-1501-415d-8112-d932cb83b2ae.png">

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This was fixed in #24 . It will be released in 1.0.0-beta.2
