### ISSUE TITLE
Multiselect array filtering modes not usable

### ISSUE THREAD

**Issue by danicc097** [KevinVandy/mantine-react-table#296]
### mantine-react-table version

v2.0.0-beta.0

### react & react-dom versions

18

### Describe the bug and the steps to reproduce it

No `arr*` options to select filter modes in multiselect. Any other filter mode is shown as an option.

Steps:
- Select filter by `state` -> nothing renders
- Select any item -> mode is Contains and still no filter options rendered

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-bkou1d?file=src%2FTS.tsx,package.json,src%2Fmain.tsx

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Hi there, in the meantime you can manually import the array sorting functions and use them as a custom filter.

**Comment by alessandrojcm** [comment]
This is fixed in the latest beta.
