### ISSUE TITLE
Row disappears post filter with null dates

### ISSUE THREAD

**Issue by viandika** [KevinVandy/mantine-react-table#297]
### mantine-react-table version

2.0.0-beta.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When a row has null in date value, following the guide with `accessorFn: (originalRow) => new Date(originalRow.hireDate)`, the resulting row will be `new Date(null)` which is equivalent to 1/1/1970.
if a filter is performed on the column and the remove the filter, the row disappears.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-zq6a8y
1. input and minimum date filter on the `Hire Date` column
2. clear the filter
3. Notice there is one less row on the table

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
It might be worth to try reproduce this using TanStack table directly instead of MRT to rule out is not a bug with TanStak itself.
