### ISSUE TITLE
accessorFn causes exception when state.isLoading is true and data is empty array

### ISSUE THREAD

**Issue by cristiancundari** [KevinVandy/mantine-react-table#304]
### mantine-react-table version

1.3.4 & v2

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

In a situation where the table data are fetched from a server; specifically, when the `data` array is still empty while awaiting the server response and the `isLoading` state is set to true to indicate that the data is not yet ready, an exception occurs if a `columnDef` employs an `accessorFn` to access a nested object property. This leads to application crash.

To replicate the problem, simply set the table `data` prop to an empty array, set the `isLoading` state to `true`, and utilize any `columnDef` that accesses a nested object property.

It appears that the `accessorFn` is invoked even when no data is present, causing `row.name` to be `undefined`.

### Minimal, Reproducible Example - (Optional, but Recommended)

```javascript
const columns = useMemo<MRT_ColumnDef<Person>[]>(
  () => [
    {
      accessorFn: (row) => row.name.firstName,
      id: 'firstName',
      header: 'First Name',
    },
  ],
  [],
);

const table = useMantineReactTable({
  columns,
  state: {
    isLoading: true
  },
  data: [], //must be memoized or stable (useState, useMemo, defined outside of this component, etc.)
});
```

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Hi there, could you please post a complete example? I cannot seem to [reproduce](https://codesandbox.io/p/devbox/github/KevinVandy/mantine-react-table/tree/v2/apps/mantine-react-table-docs/examples/basic/sandbox?file=%2Fsrc%2FTS.tsx) this.
