### ISSUE TITLE
Column filter 'date-range' not resetting correctly

### ISSUE THREAD

**Issue by vuckookv3** [KevinVandy/mantine-react-table#316]
### mantine-react-table version

2.0.0-beta.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When using 'date-range' filter, you input some value in Min or Max, and then clear that value.. No data is shown afterwards...
This is also happening on your official example, which I provided.

What I could notice is, initial state of those filters are [undefined, undefined], but when the field gets cleared, it becomes [null, undefined]... Maybe that could help.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/devbox/github/KevinVandy/mantine-react-table/tree/v2/apps/mantine-react-table-docs/examples/customize-filter-variants/sandbox

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
This was fixed in #302, it has not been released yet
