### ISSUE TITLE
Row selection not updating after adding filters

### ISSUE THREAD

**Issue by vuckookv3** [KevinVandy/mantine-react-table#317]
### mantine-react-table version

^2.0.0-beta.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

1. Select all rows (it should say 10 of 12 rows selected)
2. Export Selected Rows (all 10 rows exported, all good)
3. Add any filter (for example, search City and write "ea")
4. It should say 4 of 4 rows selected
5. Export Selected Rows (it exports all 10 again)

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/devbox/github/KevinVandy/mantine-react-table/tree/v2/apps/mantine-react-table-docs/examples/export-to-pdf/sandbox

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by vuckookv3** [comment]
I should also mention to just change `columnFilterDisplayMode: 'popover',` to `subheader` or just comment out that line, to get filters to work (maybe that's another bug with popover?)

**Comment by alessandrojcm** [comment]
Hi there, so I've been playing around with this. And although I can reproduce this behavior with both `popover` and `subheader` I do not believe this is a bug. The reasons is that filtering the rows does not alter the selection even in TanStack Table [itself](https://codesandbox.io/p/devbox/github/tanstack/table/tree/main/examples/react/row-selection?embed=1&theme=dark), however, to achieve the behaviour you want, you can use [`getFilteredSelectedRowModel`](https://tanstack.com/table/latest/docs/guide/row-models#available-row-models-on-table-instance) instead. This comes directly from TanStack so the typings won't match `MRT_TableRow`.

**Comment by vuckookv3** [comment]
Hey,

what I did in the end, was keeping `columnFilters` in a state.
And then I just resetted the selections every time filters change, like so:

`useEffect(() => { table.resetRowSelection(); }, [columnFilters]);`

So I am forcing the user to click again on "Select All" checkbox, so that I can get a new selection.

**Comment by alessandrojcm** [comment]
Great that you solved it! I think you should try with the method I mentioned above though, it might allow you to implement the same functionality without the extra useEffect
