### ISSUE TITLE
v2 multi-select filter UI is broken.

### ISSUE THREAD

**Issue by Nasubikun** [KevinVandy/mantine-react-table#318]
### mantine-react-table version

2.0.0-beta.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When filterVariant set to "multi-select", the X button next to it doesn't work and the place holder keeps to be shown. 

https://v2.mantine-react-table.com/docs/guides/column-filtering

You can see the bug in the document. (State filter)

This works well with MRT v1.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://v2.mantine-react-table.com/docs/guides/column-filtering

State filter in the mid of this document.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
As a workaround, pass `clearable: true` to `mantineFilterMultiSelectProps`
