### ISSUE TITLE
Striped styles broken with renderDetailPanel

### ISSUE THREAD

**Issue by Daxble** [KevinVandy/mantine-react-table#33]
### mantine-react-table version

1.0.0-beta.2

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When using renderDetailPanel all rows appear striped, this appears to be caused by renderDetailPanel rendering an additional tr element. Disabling detailPanel fixes the issue.

### Minimal, Reproducible Example - (Optional, but Recommended)

```
const columns = useMemo<
  MRT_ColumnDef<{
    id: string;
    name: string;
  }>[]
>(
  () => [
    {
      header: "ID",
      accessorKey: "id",
    },
    {
      header: "Name",
      accessorKey: "name",
    },
  ],
  []
);

return (
  <MantineReactTable
    columns={columns}
    data={[
      {
        id: "1",
        name: "John Doe",
      },
      {
        id: "2",
        name: "Jane Doe",
      },
    ]}
    renderDetailPanel={() => {
      return null;
    }}
    mantineTableProps={{
      striped: true,
    }}
  />
);
```

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
You will just have to style them a bit differently manually. See a similar issue

https://github.com/KevinVandy/material-react-table/issues/245

**Comment by Daxble** [comment]
Ah, easy enough fix. Thank you for the quick response.
