### ISSUE TITLE
Scrollbar is over header and not just body

### ISSUE THREAD

**Issue by jporchy** [KevinVandy/mantine-react-table#331]
### mantine-react-table version

1.3.4

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Unless I'm missing something, there does not seem to be a way to make the scrollbar go over just the body and not the header.
![image (1)](https://github.com/KevinVandy/mantine-react-table/assets/164030834/71919724-6d7d-490a-9f43-955691b17452)

### Minimal, Reproducible Example - (Optional, but Recommended)

You can even see this happening at the table in https://www.mantine-react-table.com/docs/guides/virtualization#enable-row-virtualization-demo

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Hi, this is intended behavior, HTML tables are not really meant to have scrolling bodies but on the table as a whole. So the workaround is using position sticky on the header so it stays at the bottom while the rest of the table scrolls.
