### ISSUE TITLE
Some func missing

### ISSUE THREAD

**Issue by scascalespAV** [KevinVandy/mantine-react-table#335]
### mantine-react-table version

1.3.4

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

Hello

I see many things that don't work... something escapes me and I've already read the doc:
- How do I put an id to th?
- How do I apply a default filter to the table?
- How do I make a fintro through javascript? For example, when pressing an input that has nothing to do with the table

Thank you

### Minimal, Reproducible Example - (Optional, but Recommended)

```
{
            accessorKey: 'ignored',
            header: 'Ignorado',
            headerProps: { id: 'header-ignored' }, /*ko?*/
            Cell: ({ cell }) => {
               return (
                  <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                     <Checkbox id={`cell-ignored-${cell.row.index}`} checked={cell.getValue()} readOnly />
                  </div>
               );
            },
            filterVariant: 'checkbox',
            /*ko*/
            // filterValue: false,
            // filterRowPlaceholder: '',
            // filter: {
            //    defaultValue: false
            // }
            //filterFn: (row, columnId, filterValue) => {
            //   // Custom filter function logic
            //   if (filterValue === 'true') {
            //     return row.getValue(columnId) === true;
            //   } else if (filterValue === 'false') {
            //     return row.getValue(columnId) === false;
            //   }
            //   return true;
            // },
         },
```

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
You're not using the correct props that are documented at all. It looks like you are trying to guess and make up what you think that the props should be called. Read the prop tables in the docs or better, use TypeScript.

**Comment by scascalespAV** [comment]
Ok! "Read the prop tables in the docs " I have looked at the documentation but I couldn't find it, probably due to my mistake. Could you send me the link?. Thx!

**Comment by KevinVandy** [comment]
https://www.mantine-react-table.com/docs/api

**Comment by scascalespAV** [comment]
Hello. That is general doc. I search for example "id on th" or something like that and... no results. Can you post some example or direct link please?

-How do I put an id to th?
-How do I apply a default filter to the table?
-How do I make a fintro through javascript? For example, when pressing an input that has nothing to do with the table

Thx

**Comment by KevinVandy** [comment]
I'm sorry, but you're not looking very hard if you don't see many examples for how to do all that.
