### ISSUE TITLE
[BUG] Row action menu items not shown if initial state has `columnOrder`

### ISSUE THREAD

**Issue by goliatone** [KevinVandy/mantine-react-table#34]
### mantine-react-table version

1.0.0-beta.2

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

If we set `columnOrder` in `initialState`, then action menu is not rendered.

### Minimal, Reproducible Example - (Optional, but Recommended)

```tsx
return (
        <MantineReactTable
            data={records.data}
            columns={columns}
            enableRowActions
            renderRowActionMenuItems={({ row }) => (
                <Box component={Stack}>
                    <Button onClick={() => actionHandler(row, 'edit')}>
                        Edit
                    </Button>
                    <Button onClick={() => actionHandler(row, 'run')}>
                        Run
                    </Button>
                    <Button onClick={() => actionHandler(row, 'cancel')}>
                        Cancel
                    </Button>
                </Box>
            )}
            initialState={{
                // columnOrder: [
                //     'id',
                //     'type',
                //     'description',
                //     'active',
                //     'lastrun_at',
                //     'actions',
                // ],
            }}
        />
    );
```

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
The solution to this is to simply add `'mrt-row-actions'` to your column order array initial state. More about the built-in columns here: https://www.mantine-react-table.com/docs/guides/display-columns
