### ISSUE TITLE
Hidden Columns and Updating Rows

### ISSUE THREAD

**Issue by sakgoyal** [KevinVandy/mantine-react-table#343]
### mantine-react-table version

2.0.0-beta.4

### react & react-dom versions

v18

### Describe the bug and the steps to reproduce it

* have column with `id` column
* hide column with `initialState:{columnVisibility:{id : false}}`
* edit row and send new data to api
* api data does not contain the id row
* making the column visible again and the api receives the id key. when hidden, api does not receive id key so it is impossible to update correctly. 

* I just want a way to have a hash string as a key but hide it so the user does not see a long has key

I had to fix this manually in my code by doing this:

```ts
const handleEditUser: MRT_TableOptions<User>['onEditingRowSave'] = async ({ values, exitEditingMode, row }) => {
		await updateRow({ ...values, id : row.original.id });
		exitEditingMode();
	};
```

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-j8fz9d?file=src%2FTS.tsx

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by sakgoyal** [comment]
I suspect something has to change here, but im not sure exactly how:
https://github.com/KevinVandy/mantine-react-table/blob/edfb182b6d0a7b2cc5eb7d6bf3ee94cd47aa848f/packages/mantine-react-table/src/components/buttons/MRT_EditActionButtons.tsx#L77

**Comment by alessandrojcm** [comment]
I assume there is a reason here why the edited data does not contain hidden columns? @KevinVandy

**Comment by yann-combarnous** [comment]
Same issue here, "id" vanished so api call to edit will fail.

**Comment by alessandrojcm** [comment]
Hi, sorry for the late reply. You can use `row.original` to get the row data as it was passed into the table.

**Comment by sakgoyal** [comment]
that doesnt fix the issue though. 
that is just a work around to the bug in this package.

**Comment by alessandrojcm** [comment]
@sakgoyal it is not a bug in this package. TanStack Table, which is the underlying library used in this package, also works this way https://tanstack.com/table/latest/docs/api/features/column-visibility
