### ISSUE TITLE
Setting enableFacetedValues on a column with null values crashes the table with localCompare error

### ISSUE THREAD

**Issue by sijonelis** [KevinVandy/mantine-react-table#346]
### mantine-react-table version

2.0.0-beta.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Create a table with `enableFacetedValues: true,`, enable `multi-select` filter on a column, and pass a null value to that column

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/devbox/hopeful-hofstadter-nzjzpl?file=%2Fpackage.json%3A18%2C41&workspaceId=0fb7f49f-5f1b-4500-9a56-4441c688741b

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/mantine-react-table/assets/5102422/bb11a519-d3f6-441c-ae1f-fcab9fc69043)

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Fixed on #347
