### ISSUE TITLE
Reset Order doesn't respects positionActionsColumn="last" property

### ISSUE THREAD

**Issue by Guria** [KevinVandy/mantine-react-table#36]
### mantine-react-table version

1.0.0-beta.2

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

* Set positionActionsColumn="last" property, enableRowActions, renderRowActions
* Click Show/Hide columns
* Click Reset Order

Actions column jumps to the left

### Minimal, Reproducible Example - (Optional, but Recommended)

```jsx
 <MantineReactTable
  columns={columns}
  data={data}
  positionActionsColumn="last"
  enableColumnOrdering
  enableRowActions
  renderRowActions={({ row }) => {
    return <ActionIcon>A</ActionIcon>;
  }}
/>
```

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in v1.0.0-beta.3
