### ISSUE TITLE
enableGrouping: false on Column is not respected with enableColumnDragging on table

### ISSUE THREAD

**Issue by Guria** [KevinVandy/mantine-react-table#37]
### mantine-react-table version

1.0.0-beta.2

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

* define `enableGrouping: false` on column level
* `enableColumnDragging` and `enableGrouping` on table level

Column with `enableGrouping: false` has a drag handle and could be grouped by dragging it to toolbar.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-fpd6as-vs8gou?file=src/TS.tsx

```tsx
import React, { useMemo } from 'react';
import { MantineReactTable, MRT_ColumnDef } from 'mantine-react-table';
import { data, Person } from './makeData';

const Example = () => {
  const columns = useMemo<MRT_ColumnDef<Person>[]>(
    () => [
      {
        accessorKey: 'firstName',
        header: 'First Name',
        enableGrouping: false,  //disable column grouping for this column,
      },
      {
        accessorKey: 'lastName',
        header: 'Last Name',
      },
    ],
    []
  );

  return (
    <MantineReactTable
      columns={columns}
      data={data}
      enableColumnDragging
      enableGrouping
    />
  );
};

export default Example;
```

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in v1.0.0-beta.3
