### ISSUE TITLE
When the rows are pinned, scrolling up or down overlaps with the pinned rows. 

### ISSUE THREAD

**Issue by dvarjun** [KevinVandy/mantine-react-table#371]
### mantine-react-table version

v2

### react & react-dom versions

v18 

### Describe the bug and the steps to reproduce it

https://v2.mantine-react-table.com/docs/examples/sticky-row-pinning

Pin rows, and scroll up or down.

### Minimal, Reproducible Example - (Optional, but Recommended)

See bug description

### Screenshots or Videos (Optional)

![Screenshot 2024-07-01 at 7 48 46 PM](https://github.com/KevinVandy/mantine-react-table/assets/8991670/ad1afd81-8087-4c26-b7a8-5d8ebb85518c)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Some progress made on #373
