### ISSUE TITLE
[firefox] Dotted border not added when dragging orderable row

### ISSUE THREAD

**Issue by smiile** [KevinVandy/mantine-react-table#380]
### mantine-react-table version

2.0.0-beta.6

### react & react-dom versions

18.3.1

### Describe the bug and the steps to reproduce it

Reproduceable on the row ordering demo ( https://v2.mantine-react-table.com/docs/guides/row-ordering-dnd#enable-row-ordering-demo )
On firefox the dotted border around the rows when dragged is not visible, only the bottom border shows up on the latest table row when reaching it.
On Chrome seems to be working fine (as V1).
Haven't tried other browsers

### Minimal, Reproducible Example - (Optional, but Recommended)

https://v2.mantine-react-table.com/docs/guides/row-ordering-dnd#enable-row-ordering-demo

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Related to #327 this is a bug with firefox, see that issue for a workaround.
