### ISSUE TITLE
Cannot remove MultiSelect Chip without Dropdown being Active

### ISSUE THREAD

**Issue by ScriptedButton** [KevinVandy/mantine-react-table#381]
### mantine-react-table version

2.0.0 beta 6

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When attempting to remove an active option in the MultiSelect edit variant, it is only possible to do so when the dropdown is active.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/devbox/admiring-grothendieck-5r8kn2?file=%2Fsrc%2FApp.tsx&embed=1

### Screenshots or Videos (Optional)

https://github.com/user-attachments/assets/73b81a3f-391b-42cc-a292-e86b634d5113

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Addressed in #401, this was a fun one.
