### ISSUE TITLE
Reset order button is not working (v2)

### ISSUE THREAD

**Issue by yildirimbayrakci** [KevinVandy/mantine-react-table#384]
### mantine-react-table version

2.0.0-beta

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I encountered it locally but it can be repeated on the documentation page. After changing the column order, you can see that the "Reset Order" button does not work
https://v2.mantine-react-table.com/docs/guides/column-ordering-dnd

### Minimal, Reproducible Example - (Optional, but Recommended)

https://v2.mantine-react-table.com/docs/guides/column-ordering-dnd

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by dafer660** [comment]
Hello,

I do have the same problem, as the "Reset order" simple has a event handler noop() and I am not sure how to call `table.resetColumnOrder(true)` which should reset the state of the table.

Adding a console statement below, simply outputs the order state passed:
`
onColumnOrderChange: (updaterOrValue,) => console.log(updaterOrValue),
`

Thanks,
Daniel F.
