### ISSUE TITLE
enableRowVirtualization + createDisplayMode: 'row'

### ISSUE THREAD

**Issue by dimitrius-ion** [KevinVandy/mantine-react-table#387]
### mantine-react-table version

1.3.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

New row is not visible when enableRowVirtualization + createDisplayMode: 'row'

### Minimal, Reproducible Example - (Optional, but Recommended)

options={{
            data: data,
            createDisplayMode: "row",
            enableRowVirtualization: true,

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Hmm, this was fixed in MUI MRT a while ago, need to make sure that same logic was copied over.

**Comment by KevinVandy** [comment]
Ok. This is only available in v2

**Comment by dimitrius-ion** [comment]
Thank you
