### ISSUE TITLE
visibleInShowHideMenu: false has no effect on "Show all columns"

### ISSUE THREAD

**Issue by matttk** [KevinVandy/mantine-react-table#389]
### mantine-react-table version

2.0.0-beta.6

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

1. Disable a column from the show/hide menu via `visibleInShowHideMenu: false`.
2. Set the column to default hidden with `columnVisibility` in `initialState`. (not necessar but easier to reproduce with this step)
3. Click "Show all columns"

All columns appear, including the one that is not visible in the show/hide menu.

I would expect the disabled column (in the stackblitz example below, I chose `name.firstName`) to remain hidden, as the user cannot turn it back off, except by clicking "hide all".

As a background to why I am using this option, I want to sort the table by creation date but not show creation date to the user. If I disable sorting for creation date, the table can't be sorted by that column, so I have the column always hidden in the background, with no ability to show it. This works perfectly, until you click "show all".

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-rat1cb?file=src%2FTS.tsx

### Screenshots or Videos (Optional)

![image](https://github.com/user-attachments/assets/d112b700-f1e7-4424-a492-6ffaad9d99dd)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Hi, please confirm this still happens with the latest beta

**Comment by alessandrojcm** [comment]
Hi there, upon looking into this, I do not think it is a bug. The `visibleInShowHideMenu` only refers to the menu, not to the column being hidden/unhidden. If you wan to prevent the column from being unhidden but keep it for sorting you can:

1. Do the sorting ouside of the table (should be pretty easy if you're doing server-side pagination and using something like TanStack Query)
2. If 1. does not suit, you can attach your own `onColumnVisibilityChange` callback and prevent your column from bein unhidden.
