### ISSUE TITLE
Menu Action Items trigger aria-hidden warning

### ISSUE THREAD

**Issue by sijonelis** [KevinVandy/mantine-react-table#397]
### mantine-react-table version

2.0.0-beta.6

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Go to the example page: https://v2.mantine-react-table.com/docs/guides/row-actions#add-row-actions-menu-items

Open console

Try to click on any of the menu items

Expectation: no errors
Current state: error is shown on console

### Minimal, Reproducible Example - (Optional, but Recommended)

Reproducable on the example page: https://v2.mantine-react-table.com/docs/guides/row-actions#add-row-actions-menu-items

### Screenshots or Videos (Optional)
![image](https://github.com/user-attachments/assets/53e3fd2f-f6ea-4fec-914e-dbd7e8d600f4)

### Do you intend to try to help solve this bug with your own PR?

Maybe

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by cavalodeaco** [comment]
I am having the same issue

**Comment by sijonelis** [comment]
I checked on this more, and it seems that this issue is inherited from the
Mantine package, and is present on all their examples featuring a drop-down
modal.

I'll find some time later to open an issue there.

**Comment by alessandrojcm** [comment]
Seems fixed in the latest mantine version
