### ISSUE TITLE
Table styles are not being applied when the configuration is extracted

### ISSUE THREAD

**Issue by amitbright** [KevinVandy/mantine-react-table#399]
### mantine-react-table version

^2.0.0-beta.6

### react & react-dom versions

"next": "14.2.5", "react": "^18", "react-dom": "^18"

### Describe the bug and the steps to reproduce it

I have many tables in my project, so I created a common configuration file to use across all of them. However, when using this common configuration file for table configuration, the styles fail to apply when the configuration is imported into a page. The same styles work correctly when applied directly within the page itself, suggesting a potential issue with how the configuration file is being imported or how styles are being referenced across different components or pages.

    
**Inline Config:**
![image](https://github.com/user-attachments/assets/08b38cba-2092-4a95-b94e-0329652f0f5b)

**Extracted Config:**
    ![image](https://github.com/user-attachments/assets/722763f9-c08d-447e-a7ca-a0a69eb5c072)
    

### Minimal, Reproducible Example - (Optional, but Recommended)

GitHub Demo repo : https://github.com/amitbright/mantine-table-demo

### Screenshots or Videos (Optional)

**_app\extracted-config\page.tsx_**

![carbon](https://github.com/user-attachments/assets/aea8445d-0d13-4fd0-abba-81e4656f89a4)

**_config\getBaseTableConfig.tsx_**

![getBaseTableConfig](https://github.com/user-attachments/assets/fef60ada-5cb9-495c-a553-d22a84d5a5a0)

**_Output:_**

![image](https://github.com/user-attachments/assets/722763f9-c08d-447e-a7ca-a0a69eb5c072)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This just seems like it's a problem with your tailwind config. No idea how it would be the fault of MRT

**Comment by amitbright** [comment]
> This just seems like it's a problem with your tailwind config. No idea how it would be the fault of MRT

I've resolved the issue. It turns out I had forgotten to include the` .tsx` files in the Tailwind config.
