### ISSUE TITLE
Reset order doesn't work

### ISSUE THREAD

**Issue by DKGH** [KevinVandy/mantine-react-table#403]
### mantine-react-table version

2.0.0-beta.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Steps:
1. Create a table with. Permit column drag and drop based reordering.
2. Perform a reorder by drag and drop.
3. Attempt to use 'Reset order' to reset the order of columns.

Bug:
Reorder doesn't happen.

Expected outcome:
Reorder happens.

### Minimal, Reproducible Example - (Optional, but Recommended)

No sandbox

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Duplicate of #384 and solved in #402

**Comment by mr-burhanuddin** [comment]
@alessandrojcm when the fix will be available any expected date ??

**Comment by alessandrojcm** [comment]
Should be in the next release, not sure about ETA as I don't publish releases.

**Comment by mr-burhanuddin** [comment]
@KevinVandy can you help me with release date for this fix as i have ticket to resolve this hope you understand.

**Comment by KevinVandy** [comment]
I was trying to publish it over the weekend, but ran into some roll-up build config issue. Will try again soon.
