### ISSUE TITLE
Performance issue when using multiple tables on one page

### ISSUE THREAD

**Issue by mehdirussel** [KevinVandy/mantine-react-table#410]
### mantine-react-table version

v2

### react & react-dom versions

v18.3.1

### Describe the bug and the steps to reproduce it

Encountered performance issues when using multiple tables on one page, especially when using custom modals for CRUD operations, the page becomes totally unresponsive.

### Minimal, Reproducible Example - (Optional, but Recommended)

`
return (
    <>
      <MantineReactTable table={table1} />
      <MantineReactTable table={table2} />
    </>
  );
`

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Give an actual reproducible example. There are plenty of examples in the docs where this is not a problem.
