### ISSUE TITLE
v2 MRT exports all `@tabler/react-icons` during dev mode

### ISSUE THREAD

**Issue by sbsrnt** [KevinVandy/mantine-react-table#418]
### mantine-react-table version

2.0.0-beta.6

### react & react-dom versions

18.3.0

### Describe the bug and the steps to reproduce it

When working with `v2` MRT, the Network tab in devtools is having performance issues because for each tabler icons we get a chunk request thus producing over 5700 requests.
![image](https://github.com/user-attachments/assets/5ce93ee7-f309-45bb-a88d-b57b605a783e)

FYI I'm not using _any_ tabler icons in that repo.

### Minimal, Reproducible Example - (Optional, but Recommended)

1. Copy minimal example from https://github.com/sbsrnt/wire.
2. Open network tab and pay attention to the amount of requests that are happening (5.5k+, for each icon chunk).
3. Go to https://github.com/sbsrnt/wire/blob/master/src/layout/Content/Content.tsx and comment out `<LibrariesList />` (or in `LibrariesList` component, comment out any code related to MRT)
4. Notice that there are no chunk requests for tabler icons

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is just during dev mode without any tree shaking though, right?

**Comment by sbsrnt** [comment]
> This is just during dev mode without any tree shaking though, right?

Yeah seems to be only in dev mode.
Prod for reference: https://sbsrnt.github.io/wire/

I will update the title

**Comment by KevinVandy** [comment]
Most likely going to close this since it's expected.

**Comment by hamitaksln** [comment]
Anyway to solve this issue? It takes 10-15 seconds to load simple table when dev tools is open. I always use dev tools open so it's really making it harder to use it. It affects development experience a lot. I've tried to merge chunks in vite but couldn't find a way to do that in development mode. I really like this library but because of this issue I cannot use it.

**Comment by hamitaksln** [comment]
After hours of debugging, I found that downgrade @tabler/icons-react `^3.19.0` =>` 3.11.0` fix this issue for me.

**Comment by rossmeredith** [comment]
Yeah it's an issue with the icon library - https://github.com/tabler/tabler-icons/issues/1233

**Comment by KevinVandy** [comment]
Yeah, on further looking into that issue, it's not great. I guess a brute force solution would be to just copy the raw icon svgs into the MRT source code and remove tabler icons as a peer dep. Hopefully they just ship a fix though.

**Comment by alessandrojcm** [comment]
I will close this as it is an issue with Tabler and it's only in dev mode. Feel free to reopen if this changes.

**Comment by chrisBas** [comment]
an fyi incase anyone needs a temporary fix to improve their dev times:

https://github.com/tabler/tabler-icons/issues/1233#issuecomment-2744963177
