### ISSUE TITLE
Menu by hover on row

### ISSUE THREAD

**Issue by ofirgo1** [KevinVandy/mantine-react-table#430]
### mantine-react-table version

1

### react & react-dom versions

17

### Describe the bug and the steps to reproduce it

Hi, I want to open a menu from the side of a row when I hover over it.  I would appreciate it if you could help me with this.

### Minimal, Reproducible Example - (Optional, but Recommended)

.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Closing as this is a question, please try the Discord server.
