### ISSUE TITLE
Switching Column Filter Function from "empty|notEmpty" to "equals|contains|..." causes Exception

### ISSUE THREAD

**Issue by floriankapaun** [KevinVandy/mantine-react-table#442]
### mantine-react-table version

2.0.0-beta.7

### react & react-dom versions

^18.2.0

### Describe the bug and the steps to reproduce it

When you're setting a columns filter mode to `empty` or `notEmpty` and then switch it to another one like `equals` the following Error is thrown: `Uncaught TypeError: _value.map is not a function.`

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/devbox/dreamy-matsumoto-3cxcss?file=%2Fsrc%2FTS.tsx

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Thanks!
