### ISSUE TITLE
Pagination count for first item is wrong if data is an empty array

### ISSUE THREAD

**Issue by fredericbahr** [KevinVandy/mantine-react-table#45]
### mantine-react-table version

v1.0.0-beta.3

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

If the table data is entry and the empty state text, the pagination shows the wrong counts:

Currently it shows 1-0 of 0
It should be 0-0 of 0 as in Material React Table from my point of view

The wrong place as far as i can spot: https://github.com/KevinVandy/mantine-react-table/blob/main/packages/mantine-react-table/src/toolbar/MRT_TablePagination.tsx#L97
Probably one should check if the data is empty and then only add +1

### Minimal, Reproducible Example - (Optional, but Recommended)

<Text>{`${firstRowIndex + data.length===0 ? 0 : 1}-${lastRowIndex} ${
        localization.of
      } ${totalRowCount}`}</Text>

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in beta 4
