### ISSUE TITLE
Lexical error on css minimizer

### ISSUE THREAD

**Issue by desytech** [KevinVandy/mantine-react-table#451]
### mantine-react-table version

2.0.0-beta.7

### react & react-dom versions

18.1.0

### Describe the bug and the steps to reproduce it

Using create react app with react scripts v5.0.1 leads to a css lexer problem.

Using `unset` is not permitted on css calculations see [Formal Syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#formal_syntax)

### Minimal, Reproducible Example - (Optional, but Recommended)

```
$ react-app-rewired build
Creating an optimized production build...
Compiled with warnings.

static/css/main.ee4a7c60.css from Css Minimizer plugin
postcss-calc: ***/css/main.ee4a7c60.css:8449:3: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: unset * 1px - 1px
^..^

```

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
Fixed in #452
