### ISSUE TITLE
'multi-select' column filter Not returning the correct results

### ISSUE THREAD

**Issue by ktriek** [KevinVandy/mantine-react-table#458]
### mantine-react-table version

any

### react & react-dom versions

any

### Describe the bug and the steps to reproduce it

'multi-select' column filter Not returning the correct results, in the demo, if you select "Cal" state, it should not return results for "California".
An `equals` check should be used instead of `contains`

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-9jr7p9uw-bjvpwces?file=src%2FTS.tsx,src%2FmakeData.ts

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by ktriek** [comment]
As a workaround right now,  a custom filter is working as expected
```ts
const multiSelectFilterFn = (row: Row<any>, columnIds: string, filterValue: string[]) => {
  return (filterValue || []).includes(row.getValue<string>(columnIds));
}; 
```

**Comment by alessandrojcm** [comment]
Sorry, but your repro uses Material React Table? This is Mantine React Table

**Comment by alessandrojcm** [comment]
In any case, in both projects you can change the `filterFn` to `equals` and it will do what you are asking, so this is not a bug.
Like so
```typescript
 const columns = useMemo<MRT_ColumnDef<Person>[]>(
    () => [
      {
        accessorKey: 'state',
        header: 'State',
        filterVariant: 'multi-select',
        filterFn: 'equals',
        filterSelectOptions: usStateList, //custom options list (as opposed to faceted list)
      },
      {
        header: 'Status',
        accessorFn: (originalRow) => (originalRow.isActive ? 'true' : 'false'), //must be strings
        id: 'isActive',
        filterVariant: 'checkbox',
        Cell: ({ cell }) =>
          cell.getValue() === 'true' ? 'Active' : 'Inactive',
        size: 170,
      },
    ],
    []
  );
```

**Comment by uqix** [comment]
We need a custom filterFn:
```typescript
export const multiSelectFilterFn = <TData extends MRT_RowData>(
    row: Row<TData>,
    columnId: string,
    filterValue: unknown[]
) => {
    return filterValue.includes(row.getValue<unknown[]>(columnId))
}

multiSelectFilterFn.autoRemove = (filterValue: unknown[]) => !filterValue.length
```
