### ISSUE TITLE
renderColumnActionsMenuItems doesnt override the whole menu

### ISSUE THREAD

**Issue by emuraton** [KevinVandy/mantine-react-table#49]
### mantine-react-table version

v0.9.5

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Column Actions Menu is not completely overrided by `renderColumnActionsMenuItems`. It seems to only replace sorting menu. From what I understand it meant to replace the whole menu content.

Here some screenshots, where I tried to use it

Action menu:
<img width="241" alt="Screenshot 2023-05-02 at 20 20 59" src="https://user-images.githubusercontent.com/10433290/235753361-63275090-216f-4844-bd0c-b8a14247077c.png">

Action menu, where I try to use `renderColumnActionsMenuItems`
<img width="213" alt="Screenshot 2023-05-02 at 20 27 20" src="https://user-images.githubusercontent.com/10433290/235753367-3c52450e-030a-4ed0-ad20-b7551b34287d.png">

Let me know that you think. I'll open a PR about it soon

PS: You library is really great. Thanks for your hard work :)

### Do you intend to try to help solve this bug with your own PR?

Yes, I am also opening a PR that solves the problem along side this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in v1.0.0-beta.7

**Comment by emuraton** [comment]
Great 🕺
