### ISSUE TITLE
mantineFilterSelectProps data attribute

### ISSUE THREAD

**Issue by Roman-Mzh** [KevinVandy/mantine-react-table#52]
### mantine-react-table version

1.0.0-beta.5

### react & react-dom versions

18.0.28/18.0.11

### Describe the bug and the steps to reproduce it

`mantineFilterSelectProps` has the following typings `Partial(SelectProps) & HTMLPropsRef<HTMLInputElement>` where both `SelectProps` and `HTMLInputElement` has `data` attribute.

There is a `filterSelectOptions` prop which partially solves the issue. If you want to pass other Select props, `mantineFilterSelectProps` will override options.

Maybe there should be an alias like `htmlData` for HTMLProps. Omitting `data` from `SelectProps` may be confusing and not reusable.

Thanks.

### Minimal, Reproducible Example - (Optional, but Recommended)

```typescript
// Type 'string[]' is not assignable to type 'readonly (string | SelectItem)[] & string'.
// Type 'string[]' is not assignable to type 'string'

const columns: MRT_ColumnDef<Reptilian>[] = [
  { filterVariant: 'select', mantineFilterProps: [{ data: ['hey'] }],
]
```

```typescript
// works fine
const columns: MRT_ColumnDef<Reptilian>[] = [
  { filterVariant: 'select', filterSelectOptions: ['hey'],
]
```

```typescript
// runtime error 'cannot read properties of undefined (reading 'map')'
const columns: MRT_ColumnDef<Reptilian>[] = [
  { filterVariant: 'select', filterSelectOptions: ['hey'], mantineFilterSelectProps: { sx: { width: 500 } }
]
```
```typescript
// same error as in example 1
// when data is manually omitted in html, filterSelectOptions is overridden by data from mantineFilterSelectProps
const columns: MRT_ColumnDef<Reptilian>[] = [
  { filterVariant: 'select', filterSelectOptions: ['hey'], mantineFilterSelectProps: { data: ['hey hey hey'], sx: { width: 500 } }
]
```

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Roman-Mzh** [comment]
looks like I was wrong and `filterSelectOptions` does not exist ;(

just tested it like in the example: https://github.com/KevinVandy/mantine-react-table/blob/main/apps/mantine-react-table-docs/examples/customize-filter-variants/sandbox/src/TS.tsx

**Comment by KevinVandy** [comment]
filterSelectOptions exists in the MUI version of MRT, but was removed in this Mantine version as the data is passed in `mantineFilterSelectProps` easy enough. There are some weird TypeScript types coming directly from Mantine though that seem to always result in an error. Will have to override that.

**Comment by KevinVandy** [comment]
This type as been fixed in beta.19
