### ISSUE TITLE
Freeze when updating data and changing sorting

### ISSUE THREAD

**Issue by fbucek** [KevinVandy/mantine-react-table#55]
### mantine-react-table version

1.0.0-beta.7

### react & react-dom versions

18.2

### Describe the bug and the steps to reproduce it

I have modified example: https://www.mantine-react-table.com/docs/examples/data-export#data-export-example
on stackblitz https://stackblitz.com/edit/github-jx1fhb?file=src%2FTS.tsx

It is fake data generator/modifier using useEffect. 
In real app, I have context datamanager, which handles data update and it is  trigered every 1 second.
In "@mui/x-data-grid": "^5" it works as expected.

Steps to reproduce:
1) run example
2) start quickly clicking on either column sort indicator. It will freeze ( tested in chrome/firefox ) Maybe filtering would also freeze app, but sorting can be triggeed quickly to find out.

Maybe this is not correct way to update data, but I did not find way to do it other way. I am using react property system, to handle updates. In c++ frameworks there were oftern methods like beforeUpdate and afterUpdate when calling own data update. But I did not find these so I assumed that it property changes are ok.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-jx1fhb?file=src%2FTS.tsx

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by fbucek** [comment]
Problem is with pagination.
When I disable pagination everything works as expected.
`enablePagination={false}`

**Comment by fbucek** [comment]
It look like this works correctly:
```
      data={personData}
      enablePagination={true}
      manualPagination={true} <-- important
      rowCount={personData.length} <-- important
```

**Comment by KevinVandy** [comment]
interesting.

**Comment by bannarisoftwares** [comment]
Facing the same issue

**Comment by KevinVandy** [comment]
This happens if you don't give a stable reference to data. See usage docs.
