### ISSUE TITLE
renderDetailPanel mount other row components even only one row is expanded

### ISSUE THREAD

**Issue by masterbater** [KevinVandy/mantine-react-table#57]
### mantine-react-table version

v1.0.0-beta.7

### react & react-dom versions

v18

### Describe the bug and the steps to reproduce it

I just logged the row in console. Expanding one will also log other rows even it is close. 
I wanted to fetch something only if its expanded. 
Is there any way to check if the current renderDetailPanel is expanded or not as a workaround ?

```react
import React, { useMemo } from "react";
import { MantineReactTable, MRT_ColumnDef } from "mantine-react-table";
import { Box, Text } from "@mantine/core";
import { data, Person } from "./makeData";

const Example = () => {
  const columns = useMemo(
    () =>
      [
        {
          accessorKey: "id",
          header: "ID",
          size: 50
        },
        {
          accessorKey: "firstName",
          header: "First Name"
        },
        {
          accessorKey: "middleName",
          header: "Middle Name"
        },
        {
          accessorKey: "lastName",
          header: "Last Name"
        }
      ] as MRT_ColumnDef<Person>[],
    []
  );

  return (
    <MantineReactTable
      columns={columns}
      data={data}
      renderDetailPanel={({ row }) => {
        console.log("row", JSON.stringify(row, null, 2));
        return (
          <Box
            sx={{
              display: "grid",
              margin: "auto",
              gridTemplateColumns: "1fr 1fr",
              width: "100%"
            }}
          >
            <Text>Address: {row.original.address}</Text>
            <Text>City: {row.original.city}</Text>
            <Text>State: {row.original.state}</Text>
            <Text>Country: {row.original.country}</Text>
          </Box>
        );
      }}
    />
  );
};

export default Example;

```

### Minimal, Reproducible Example - (Optional, but Recommended)

![image](https://github.com/KevinVandy/mantine-react-table/assets/26339988/263a8a92-464f-4c78-a1dd-482ab34e93a8)

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/mantine-react-table/assets/26339988/afb278b1-fb52-4ec1-9764-8850db3878c9)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by masterbater** [comment]
I see there is a pull request for this, this also occur with material react table
https://github.com/KevinVandy/mantine-react-table/pull/56

**Comment by KevinVandy** [comment]
Just add a `row.getIsExpanded()` check before fetching data
