### ISSUE TITLE
Customizing a component doesn't work properly

### ISSUE THREAD

**Issue by firtk** [KevinVandy/mantine-react-table#65]
### mantine-react-table version

v1.0.0-beta.8

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Customizing components doesn't work correctly. For example, setting a color for the header using mantine theme variables as described in the [docs](https://www.mantine-react-table.com/docs/guides/customize-components#the-sx-prop). Also the '!important' property is needed for the font size etc... I am sharing Stackblitz example.

Other than these, some storybook examples don't work either. [Example](https://www.mantine-react-table.dev/?path=/story/styling-theming--custom-dark-theme)

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-qsmw6h?file=src%2FTS.tsx

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by firtk** [comment]
Update

Below code doesn't work, because of [this styling](https://github.com/mantinedev/mantine/blob/8c12a76c56da51af34213f18dd67c8b72a0ddb44/src/mantine-core/src/Table/Table.styles.ts#LL45C10-L45C53) in mantine.
```
mantineTableHeadCellProps={{
  sx: (theme) => ({
    color: theme.colors.red[5],
  }),
}}
```

We can overcome this issue like below:
```
mantineTableProps={{
  sx: (theme) => ({
    '& thead tr th': {
      color: theme.colors.red[5],
    },
  }),
}}
```

**Comment by Kretiss** [comment]
Can confirm same issue in version `1.0.0-beta.17` with Mantine `6.0.14`

**Comment by KevinVandy** [comment]
The problem is that Mantine itself styles the table components from the Table element itself. So if you do want to style through cell props, you have to add ! important

**Comment by Kretiss** [comment]
@KevinVandy I am trying it like this and it doesnt work either, but in stackblitz above yes. I really dont know what I am doing wrong 

```
<MantineReactTable
            table={table}
            localization={MRT_Localization_CS}
            enableStickyHeader
            mantineTableProps={{
              sx: (theme) => ({
                '& thead tr th': {
                  color: 'yellow !important',
                },
              }),
            }}
          />
```
Localization doesnt work either, it seems like it accepts changes only from table , eg useMantineReactTable

**Comment by KevinVandy** [comment]
Oh yeah. If you pass the table instance, all other props are ignored. I'm working on fixing the Typescript types to properly warn to either pass the table instance, or just pass options as props.
