### ISSUE TITLE
React does not recognize the `rowsPerPageOptions` prop on a DOM element

### ISSUE THREAD

**Issue by marcelobaez** [KevinVandy/mantine-react-table#70]
### mantine-react-table version

1.0.0-beta.8

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When defining 'rowsPerPageOptions' props this way:

const PAGE_SIZES = ['5', '10', '15'];

<MantineReactTable
  mantinePaginationProps={{
     rowsPerPageOptions: PAGE_SIZES,
   }}
   ...someOtherProps
>

React warns in the console: "React does not recognize the `rowsPerPageOptions` prop on a DOM element"

### Minimal, Reproducible Example - (Optional, but Recommended)

const PAGE_SIZES = ['5', '10', '15'];

<MantineReactTable
  mantinePaginationProps={{
     rowsPerPageOptions: PAGE_SIZES,
   }}
   ...someOtherProps
>

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
this was fixed in one of the latest betas

**Comment by aesbetancourt** [comment]
This is not in version "^1.2.0" yet? @KevinVandy
