### ISSUE TITLE
Selecting row does not update table.getIsSomeRowsSelected()

### ISSUE THREAD

**Issue by skelawsky** [KevinVandy/mantine-react-table#71]
### mantine-react-table version

1.0.0-beta.8

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Example from documentation about  [Toolbar Customization Guide](https://www.mantine-react-table.com/docs/guides/toolbar-customization) does not work. `table.getIsSomeRowsSelected()` does not update on row selection.

### Minimal, Reproducible Example - (Optional, but Recommended)

```
renderTopToolbarCustomActions={({ table }) => {

          console.log(table.getIsSomeRowsSelected())
          return <Box sx={{ display: "flex", gap: "16px", padding: "4px" }}>
            <Button
              color="teal"
              onClick={() => {
                alert("Create New Account");
              }}
              variant="filled"
            >
              Create Account
            </Button>
            <Button
              color="red"
              disabled={!table.getIsSomeRowsSelected()}
              onClick={() => {
                alert("Delete Selected Accounts");
              }}
              variant="filled"
            >
              Delete Selected Accounts
            </Button>
          </Box>
        }}
```

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
it seems to be working fine to me

<img width="560" alt="image" src="https://github.com/KevinVandy/mantine-react-table/assets/28243511/c8891a60-8702-46b6-a094-a59e6dd33c43">
