### ISSUE TITLE
Custom action menu shows 'EDIT' menu item with editing mode set to 'table'

### ISSUE THREAD

**Issue by skelawsky** [KevinVandy/mantine-react-table#72]
### mantine-react-table version

v1.0.0-beta.10

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

With table editingMode set to 'table' and with custom actiom menu there is a bug: edit option is still present, while it should not.

### Minimal, Reproducible Example - (Optional, but Recommended)

```
<MantineReactTable
      editingMode={document?.status == "Draft" ? "table" : ""}
      enableEditing
      enableRowActions
      renderRowActionMenuItems={({ row }) => [
        <Menu.Item onClick={() => console.info("Delete")}>Delete</Menu.Item>,
      ]}
    />
```

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/mantine-react-table/assets/75502784/c1c2c28a-9e23-4638-8de8-ef2906dde345)

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Thanks. Should be fixed in v1.0.0-beta.11 along with a bunch of other editing fixes and default style changes.
