### ISSUE TITLE
Cannot read properties of undefined reading id when using grouped columns

### ISSUE THREAD

**Issue by FenderStrat85** [KevinVandy/mantine-react-table#76]
### mantine-react-table version

1.0.0-beta.8

### react & react-dom versions

17

### Describe the bug and the steps to reproduce it

 1 of 2 unhandled errors

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'id')

Call Stack
eval
node_modules/mantine-react-table/dist/esm/mantine-react-table.esm.js (1903:61)

I am getting this error. The error is caused by the creation of grouped columns under the categories of Roles and Departments. 

  const groupedRoleCols = [
    {
      id: "roles",
      header: "Roles",
      columns: roleCols,
    },
  ];

Departments is created in the same way. The role cols is an array of columns conforming to the Mantine React Table requirements. 

1) Removal of the column groupings removes the bug. 
2) I am using the same component on another page with different data values BUT the same data structure and it works WITH the grouped columns. 

This error only began occurring on Friday after I had committed some code. After committing I went to make a tiny styling change, and the error happened for the first time. Please note, at this point I was using grouped columns, this had previously not caused this error. In effect the error seems to have happened without any changes to my code, so as I am sure you can understand I am very confused. 

I have absolutely no idea why this error is occurring.

### Minimal, Reproducible Example - (Optional, but Recommended)

n/a

### Screenshots or Videos (Optional)

n/a

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by FenderStrat85** [comment]
Both of these pages use the same component with exactly the same data structure. One works, one doesn't.
<img width="1149" alt="Screenshot 2023-06-18 at 10 29 56" src="https://github.com/KevinVandy/mantine-react-table/assets/77243567/e2c4a585-3fa2-47cc-8307-9d9a8e67fc76">
<img width="1041" alt="Screenshot 2023-06-18 at 10 30 02" src="https://github.com/KevinVandy/mantine-react-table/assets/77243567/13f0d390-8129-4987-a784-a7d410361b75">

**Comment by KevinVandy** [comment]
If you're going to say that 1 table crashes and the other doesn't, I'd think that it would be extremely helpful to share the code for both tables in full. And even share the commit that caused it if possible

**Comment by FenderStrat85** [comment]
Hi Kevin,

I have managed to fix it, however hows and whys it works I'm unsure about. 

I have enableRowVirtualization and enableColumnVizualization enabled and the removal of these props solved the issue. As these prop are only needed when you have a large amount of data, it would make sense that these props could cause an issue. Although I'm still confused how removing the column grouping solved the issue on one table, but not the other. 

Oddly enough on the deployed version there were no issues, it only existed in my local dev branch. 

With this in mind, could it be a caching issue inside Chrome? 

Thanks for a great package, the level of detail you can go into is amazing!
