### ISSUE TITLE
Infinite rerendering when using useMantineReactTable if enablePagination is true or not supplied

### ISSUE THREAD

**Issue by masterbater** [KevinVandy/mantine-react-table#81]
### mantine-react-table version

v1.0.0-beta.21

### react & react-dom versions

v18

### Describe the bug and the steps to reproduce it

Use this component, and see console, it logs the data indefinitely

```typescript
"use client";
import React, { useMemo } from "react";
import {
  MantineReactTable,
  useMantineReactTable,
  type MRT_ColumnDef,
} from "mantine-react-table";

const Table= () => {
  const defaultValue = {
    a: "Test",
    b: "Test",
    c: "Test",
    d: "Test",
    e: "Test",
  };
  const data = [defaultValue];

  console.log("data", JSON.stringify(data, null, 2));

  const columns = useMemo<MRT_ColumnDef<typeof defaultValue>[]>(
    () => [
      {
        accessorKey: "a",

        header: "First Name",
      },
      {
        accessorKey: "b",

        header: "Last Name",
      },
      {
        accessorKey: "c",

        header: "Address",
      },
      {
        accessorKey: "d",

        header: "City",
      },
      {
        accessorKey: "e",

        header: "State",
      },
    ],
    []
  );

  const table = useMantineReactTable({
    columns,
    data,
    enablePagination: true, // true or remove this property to replicate
  });
  return <MantineReactTable table={table} />;
};

export default Table;

```

### Minimal, Reproducible Example - (Optional, but Recommended)

I modify Basic Example and put data into inside the component
https://codesandbox.io/p/sandbox/funny-davinci-v6t5kl

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is because you are defining your data in an unsafe/unstable way. You have to either store `data` in `useState` or `useMemo`. Every time the data updates in the table, it will cause the `useMantineReactTable` hook to re-render, which causes the data to be redefined, which causes.... infinite loop. Just give your `data` a stable reference and it will work.

From the [Usage](https://www.mantine-react-table.com/docs/getting-started/usage) docs:

<img width="1257" alt="image" src="https://github.com/KevinVandy/mantine-react-table/assets/28243511/19e3595b-f65f-4870-946e-bd478ce34eb5">

**Comment by KevinVandy** [comment]
This issue did prompt me to remember to add a bunch more comments throughout the examples in the docs to remind devs of this

<img width="833" alt="image" src="https://github.com/KevinVandy/mantine-react-table/assets/28243511/2400b071-a25b-4d07-b296-ec0896e1c21d">

**Comment by masterbater** [comment]
> This issue did prompt me to remember to add a bunch more comments throughout the examples in the docs to remind devs of this
> 
> 
> 
> <img width="833" alt="image" src="https://github.com/KevinVandy/mantine-react-table/assets/28243511/2400b071-a25b-4d07-b296-ec0896e1c21d">
> 
> 

I see, I never encountered this before and Im also using manualPagination it doesnt affect whether I memoize data also if enablePagination false doesnt do infinite rerender. Thanks for replying I know this is beta Ill just wrapped my data in memo just to be sure.
