### ISSUE TITLE
State isLoading is not working since V1.0.0-beta.19

### ISSUE THREAD

**Issue by raw2DD4** [KevinVandy/mantine-react-table#83]
### mantine-react-table version

V1.0.0-beta.19

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Since version beta.19 the parameter for state: isLoading is not working

### Minimal, Reproducible Example - (Optional, but Recommended)

```
return (
    <MantineReactTable
      autoResetPageIndex={false}
      columns={columns}
      data={tableData}
      enableSorting={false}
      enableEditing={true}
      enablePagination={false}
      editingMode="cell"
      enableRowVirtualization={true}
      state={{ isLoading }}
      mantineProgressProps={() => ({
        variant: "determinate", // if you want to show exact progress value
        value: loadingProgress, // value between 0 and 100
      })}
      rowVirtualizerProps={{
        overscan: 10, // adjust the number or rows that are rendered above and below the visible area of the table
        estimateSize: () => 70, // if your rows are taller than normal, try tweaking this value to make scrollbar size more accurate
      }}
      initialState={{ showGlobalFilter: true }}
    />
  );
```

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
There was a change that if your data is already there will full row values, the cell data will just be shown instead

**Comment by raw2DD4** [comment]
Thank you for very quick replay. And is there a possibility to get loading animation like it was before?

**Comment by KevinVandy** [comment]
It should still work. What do your column definitions look like? You can see them still working on the docs site, right?

**Comment by raw2DD4** [comment]
I create dynamically depending on the content, below is an example: ( I also sometimes use <Select> as Cell )
```
      table.unshift({
        id: "outNo",
        accessorFn: (info) => {
          return info.outNo + 1;
        },
        header: t("NUMBER"),
        enableEditing: false,
      });
```

**Comment by raw2DD4** [comment]
In beta.24 it's working:) Thank you very much for help
